# Generated by Django 4.2.6 on 2024-02-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelunits',
            name='bcontent',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='modelunits',
            name='bmail',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelunits',
            name='bresponse',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='modelunits',
            name='bsubject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelunits',
            name='btime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelunits',
            name='bweb',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='modelunits',
            name='bname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
