# Generated by Django 4.2.6 on 2024-02-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0002_modelunits_bcontent_modelunits_bmail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelunits',
            name='bweb',
        ),
    ]
