# Generated by Django 4.2.6 on 2024-02-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0003_remove_modelunits_bweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelunits',
            name='bresponse',
            field=models.TextField(default='', null=True),
        ),
    ]
